### ISSUE TITLE
中間報告レビュー

### ISSUE THREAD

**Issue by kerochelo** [nanako45a/find_library#118]
@nanako45a 
リリースお疲れ様でした。
下記にフィードバック内容を上げましたので、ご確認ください！

## フィードバック
- controllerは全体的にリファクタ&rubocopを通しておく（chatGPTに相談しながら進めるといいです）
- 編集画面の更新ボタンの位置はフォームの下に置いておく
- node_modulesに入っているパッケージはgitで管理しないようにする
- オートコンプリートが動いてないので修正する
- ログアウトはヘッダーではなくマイページの中に導線を移動させる
- 技術+α：で近くの図書館をレコメンドする画面では地図上で表示するようにするなど、別のUIを準備しておくと良さそうです
- 技術+α：図書館一覧はHotwireのturbo frameを利用して表示するようにする（参考：https://zenn.dev/shita1112/books/cat-hotwire-turbo/viewer/turbo-frames）

上記内容をタスクに落とし込んでissue化して、本リリースまでの見積もりを再度行って見てください。
できましたら、こちらのスレッドに共有いただければでございます！

**Comment by nanako45a** [comment]
@kerochelo
