### ISSUE TITLE
本リリースレビュー依頼

### ISSUE THREAD

**Issue by nanako45a** [nanako45a/find_library#137]
土屋講師お疲れ様です！
中間レビューのissueが完了しました。
ご確認のほどよろしくお願いいたします🙇
アプリケーション名：「FindLibrary」
アプリケーションURL：https://cryptic-headland-70938-ab332c316ec4.herokuapp.com/

**Comment by Tsuchiya2** [comment]
お疲れ様です。
以下、レビューした際の気になった箇所になります！
上から順に優先度が高いものになってます。
（最後のJavaScript管理は、優先度低めで大丈夫です）

- 使用していないファイル（xxx_helper.rb・使用されていないビューファイルなど）を削除
- 独自ドメイン対応
- ファビコン対応
- Rubocop通す（インデントのズレも修正）
- テストコードを書く
- README.mdを就活用に修正
- ビューファイルに書かれているscriptはRailsのJavaScript管理の方法に移行していく

本リリースを行い、就活と並行して上記も対応していくと良いかと思います！（README.md修正までは必須）

引き続き頑張ってください！

**Comment by nanako45a** [comment]
レビューありがとうございます！引き続き頑張っていきます！✨
